/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HauntedHouse;

import HauntedHouse.Gui.GameWindow;

/**
 * Main Class
 * @author Jorge Moreira, Miguel Costa
 */
public class App {
    /**
     * main method
     * @param args
     */
    public static void main(String[] args) {
        new GameWindow();
    }
}