/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HauntedHouse;

import HauntedHouse.MapDefinitions.MapExceptions;
import HauntedHouse.Menu.Menu;
import HauntedHouse.Menu.MenuExceptions;
import Structures.BinaryTree.BinaryTreeExceptions;
import Structures.Graph.GraphExceptions;
import Structures.Lists.ListExceptions;

import java.io.IOException;

/**
 * Main Class
 *
 * @author Jorge Moreira, Miguel Costa
 */
@Generated
public class App {

    /**
     * Menu instance
     */
    private static Menu menu = new Menu();

    /**
     * Main method
     *
     * @param args
     */
    @Generated
    public static void main(String[] args) throws MapExceptions, MenuExceptions,
            GraphExceptions, IOException, ListExceptions, BinaryTreeExceptions {
        menu.mainMenu();
    }
}