/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HauntedHouse;

/**
 * Main Class
 * @author Jorge Moreira, Miguel Costa
 */
@Generated
public class App {
    /**
     * main method
     * @param args
     */
    @Generated
    public static void main(String[] args) {
        System.out.println("");
    }
}
