/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HauntedHouse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    public void appHasAGreeting() {
        Assertions.assertEquals(1,1);
    }
}
